# Generated by Django 3.2.17 on 2023-02-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmaster',
            name='post_category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='category.categorymaster'),
        ),
    ]
