# Generated by Django 3.2.17 on 2023-02-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='ads_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
