# Generated by Django 3.2.17 on 2023-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_ads_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_ads', models.ImageField(null=True, upload_to='otherads')),
            ],
            options={
                'db_table': 'other_ads',
            },
        ),
    ]
